import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tabular = localFont({
  src: [
    {
      path: "../public/fonts/Tabular-Variable.ttf",
      style: "normal",
    },
    {
      path: "../public/fonts/Tabular-VariableItalic.ttf",
      style: "italic",
    },
  ],
  variable: "--font-tabular",
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const charm = localFont({
  src: [
    {
      path: "../public/fonts/Charm-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Charm-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-charm",
});

const notoSerifGeorgian = localFont({
  src: [
    {
      path: "../public/fonts/NotoSerifGeorgian-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/NotoSerifGeorgian-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-noto-serif-georgian",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tabular.variable} ${dmSans.variable} ${charm.variable} ${notoSerifGeorgian.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
